# for get_url HTTPS
- name: Install ca_root_nss
  pkgng: name=ca_root_nss state=present

# for unarchive
- name: Install gtar
  pkgng: name=gtar state=present

- name: Create .d dir
  file: dest={{ item }} state=directory
  with_items:
    - /usr/local/etc/newsyslog.conf.d
    - /usr/local/etc/syslog.d
