- name: Install gtar
  pkgng: name={{ item }} state=present
  with_items:
    - gtar

- name: Create .d dir
  file: dest={{ item }} state=directory
  with_items:
    - /usr/local/etc/newsyslog.conf.d
    - /usr/local/etc/syslog.d
